### ISSUE TITLE
persistence layer ?

### ISSUE THREAD

**Issue by 00imvj00** [tekjar/rumqttd#10]
hey, nice work. 

I just wanted to know if you have any plans to persist offline messages, like if I need to restart my broker, then also all pending message should not go away. 

if you have any plans, then I might work on that.

what do you think?

**Comment by tekjar** [comment]
Yeah mosquitto has this feature. We can definitely do this but I'd implement this as a plugin. I want to keep the core deamon as light weight as possible allowing it to run in small embedded devices like onion/raspberry pi as well as cloud.

I have plans for clustering using elixir plugin. You might be interested in this :)

**Comment by 00imvj00** [comment]
Got it.
