### ISSUE TITLE
Release a separate MQTT library

### ISSUE THREAD

**Issue by bestouff** [tekjar/rumqttd#3]
Hi !

Nice work. Would it be possible for you to release a separate library, or make your MQTT library usable for people wanting to add tokio-mqtt capabilty in their code ?

Regards

**Comment by tekjar** [comment]
Hi @bestouff . I'm not sure if I understand the question completely. If you want a library to parse mqtt packets that could be pluggable in tokio, I have a forked version of [mqtt3](https://github.com/tekjar/mqtt3) suitable for it. By the way, this is a broker implementation. I also have a client version but I'm stuck at client reconnections.

**Comment by bestouff** [comment]
Yes that's what I wanted, client-side. I'll have a look at your fork, thanks.

**Comment by tekjar** [comment]
@bestouff If you are writing a client, you can directly use codec from this crate along with mqtt3

**Comment by bestouff** [comment]
Perfect, thanks @tekjar !
